apiVersion: apps/v1
kind: Deployment
Metadata:
 name: deploy1
spec:
 replicas: 2
 selector:
  matchLabels:
   app: app1
 template:
  metadata:
   labels:
    app: app1
  spec:
   containers:
    - name: app
      image: youssefsaid/app:1.0
---
apiVersion: v1
kind: Service
Metadata:
 name: srv1
spec:
 selector:
  app: app1
 ports:
  - name: port1
    port: 2000
    targetPort: 2000
    nodePort: 32000
 type: NodePort
